### ISSUE TITLE
Surface cluster name in logdna logs

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-observability-agents#89]
### Description

Use case: Surface the cluster name in the logdna logs so that consumer can filter by cluster name.

Approach:
- Add the cluster name as one of the tags passed to the logdna agent https://github.com/terraform-ibm-modules/terraform-ibm-observability-agents/blob/b52b75c68ba440c007df11063686e20bdce68dba/main.tf#L106
- Introduce a new variable (with default set to true). logdna_add_cluster_name

**Comment by Aashiq-J** [comment]
PR merged. closing this issue.
