### ISSUE TITLE
Surface cluster name in sysdig

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-observability-agents#90]
### Description

Currently the cluster id is surfaced in Sysdig. See attached screenshot.
![image](https://user-images.githubusercontent.com/16447795/229776933-107965b8-f5e0-4135-9a3b-465d23b29c1e.png)

For comparison, using the out of the box sysdig integration https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/ob_monitoring, the cluster name is surfaced. See second screenshot.

![image](https://user-images.githubusercontent.com/16447795/229777033-f78c9f5e-4b2a-402f-b85c-aca774850b07.png)

**Comment by Aashiq-J** [comment]
PR merged. closing this issue.
